### ISSUE TITLE
Construtor com null?

### ISSUE THREAD

**Issue by osmarbraz** [PoweredTable/sist-emprestimo-de-ferramentas#71]
Qual a razão de atribuir null?
Revisem o conteúdo da aula.

public Ferramenta() {
        this.id = null;
        this.nome = null;
        this.marca = null;
        this.preco = null;
    }

**Comment by PoweredTable** [comment]
Boa tarde,

Agradecemos pela abertura da issue apresentando algo que fere alguns princípios de design de código, porém gostaríamos que as próximas vezes fosse incluída uma descrição mais detalhada do problema encontrado.

**Comment by osmarbraz** [comment]
Não detalhei pois basta seguir o exemplo apresentado em sala.
